version: "3.9"
services:
  rabbitmq2:
    image: rabbitmq:3-management
    # container_name: sd05rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "student"
      RABBITMQ_DEFAULT_PASS: "student"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672